package com.capstone.capstone.model;

public enum TipoAttrezzo {
	ACCESSORI,
	BILANCIERI,
	ATTREZZI_CORPO_LIBERO,
	CROSS_TRAINER,
	ABBIGLIAMENTO_FITNESS,
	MANUBRI,
	PANCHE,
	TAPIS_ROULANT,
	VOGATORE,
	ABBIGLIAMENTO_CICLISMO
}
